version: '3.8'
services:

  redis:
    image: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: kurs_drf
    entrypoint:
      - /migrate
    command:
      - /start
    ports:
      - '8000:8000'
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: kurs_drf
    env_file:
      - .env
    ports:
      - '5432:5432'

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    command: /start-celery-worker
    env_file:
      - .env
    depends_on:
      - redis
      - app



  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    command: /start-celery-beat
    env_file:
      - .env
    depends_on:
      - redis
      - app

