# Generated by Django 4.2.6 on 2023-10-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='Periodicity',
            new_name='periodicity',
        ),
    ]
